services:
  postgres:
    container_name: springboot-ms-postdb
    image: postgres
    environment:
      POSTGRES_USER: kevinjia
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: